#define ALL_ARG               'a'
#define ALMOST_ALL_ARG        'A'
#define IGNORE_BACKUPS_ARG    'B'
#define L_ARG                 'l'
#define INODE_ARG             'i'
#define NO_GROUP_ARG          'G'
#define FULL_TIME_ARG         'T'
#define FULL_SIZE_ARG         'S'
#define DECIMAL_SIZE_ARG      'D'
#define NUMERIC_UID_GID_ARG   'n'
#define REVERSE_ARG           'r'
#define SORT_ARG              's'
#define S_NAME_ARG            'n'
#define S_X_ARG               'x'
#define S_TIME_ARG            't'

#define ALL_ARG_W             "--all"
#define ALMOST_ALL_ARG_W      "--almost-all"
#define IGNORE_BACKUPS_ARG_W  "--ignore-backups"
#define AUTHOR_ARG_W          "--author"
#define INODE_ARG_W           "--inode"
#define NO_GROUP_ARG_W        "--no-group"
#define FULL_TIME_ARG_W       "--full-time"
#define FULL_SIZE_ARG_W       "--full-size"
#define DECIMAL_SIZE_ARG_W    "--decimal"
#define NUMERIC_UID_GID_ARG_W "--numeric-uid-gid"
#define NO_DIRS_TOP_ARG_W     "--no-group-dirs"
#define REVERSE_ARG_W         "--reverse"
